### ISSUE TITLE
Cannot Load Such File

### ISSUE THREAD

**Issue by jacksonhk** [VictorBersy/eve-online-killboard-to-slack#2]
I am running Ruby 2.0 and bundle install went smoothly.
So I have no idea what went wrong to cause this, any help is much appreciated!

Also, please let me know your in-game name, I want to send cake!

```
/usr/local/ruby20/lib64/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require': cannot load such file -- slack-notifier (LoadError)
        from /usr/local/ruby20/lib64/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'
        from /home/origami/public_html/slack/kb/src/eve_online_killboard_to_slack.rb:7:in `<module:EveKillboardToSlack>'
        from /home/origami/public_html/slack/kb/src/eve_online_killboard_to_slack.rb:3:in `<top (required)>'
        from /usr/local/ruby20/lib64/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'
        from /usr/local/ruby20/lib64/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'
        from eve_online_killboard_to_slack:2:in `<main>'
```

**Comment by VictorBersy** [comment]
Hey @jacksonhk ! 

Did you run `bundle install` ? It looks like the gem `slack-notifier` is not installed.

**Comment by VictorBersy** [comment]
Closing as this has been open since one week with no response. @jacksonhk if this is still a problem, please feel free to reopen the issue :)
